
package org.tektutor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RPNCalculator", targetNamespace = "http://tektutor.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RPNCalculator {


    /**
     * 
     * @param strRPNMathExpression
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "calculateReturn", targetNamespace = "http://tektutor.org")
    @RequestWrapper(localName = "calculate", targetNamespace = "http://tektutor.org", className = "org.tektutor.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://tektutor.org", className = "org.tektutor.CalculateResponse")
    public double calculate(
        @WebParam(name = "strRPNMathExpression", targetNamespace = "http://tektutor.org")
        String strRPNMathExpression);

}
